#!/usr/bin/env node
// Regenerates src/data/photos.ts from photos/*.json and reports which recipes still lack a photo.
//
//   node scripts/photos/manifest.mjs
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { META_DIR, ROOT, readJson } from './common.mjs';

export function readMeta() {
  let files = [];
  try {
    files = readdirSync(META_DIR).filter((f) => f.endsWith('.json'));
  } catch {}
  return files.map((f) => readJson(join(META_DIR, f), null)).filter(Boolean);
}

export function writeManifest({ quiet = false } = {}) {
  const metas = readMeta().sort((a, b) => a.id.localeCompare(b.id));
  const photos = metas.filter((m) => m.photo);
  const body = photos.map((m) => `  ${JSON.stringify(m.id)}: ${JSON.stringify(m.photo)},`).join('\n');
  writeFileSync(
    join(ROOT, 'src/data/photos.ts'),
    '// GENERATED by scripts/photos/manifest.mjs from photos/*.json. Do not edit by hand.\n' +
      "import type { RecipePhoto } from '../types.ts';\n\n" +
      `export const PHOTOS: Readonly<Record<string, RecipePhoto>> = {${body ? `\n${body}\n` : ''}};\n`,
  );
  if (!quiet) console.log(`src/data/photos.ts: ${photos.length} photos, ${metas.length - photos.length} recipes marked "no photo"`);
  return metas;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const metas = writeManifest();
  const { RECIPES } = await import(join(ROOT, 'src/data/recipes/index.ts'));
  const byId = new Map(metas.map((m) => [m.id, m]));
  const none = metas.filter((m) => !m.photo);
  const pending = RECIPES.filter((r) => !byId.has(r.id));
  if (none.length) console.log(`\nNo suitable photo (${none.length}):\n${none.map((m) => `  ${m.id}: ${m.reason}`).join('\n')}`);
  if (pending.length) console.log(`\nNot searched yet (${pending.length}):\n  ${pending.map((r) => r.id).join('\n  ')}`);
}
